### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by jessjaco** [mstrimas/gdal-summarize#2]
The Readme says the default summary function is 'sum', but in the code it is 'mean'.

**Comment by mstrimas** [comment]
thanks for catching that, should be fixed now

**Comment by qdread** [comment]
It still says sum for the first two code examples.

**Comment by mstrimas** [comment]
Thanks for catching that, hopefully it's fixed now!

**Comment by qdread** [comment]
Thanks go to you for creating this very useful piece of software! 🥇
