### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by gusmacaulay** [mstrimas/gdal-summarize#3]
Running the script with two .tif files, I get an error in the nodata handling.  

0...Traceback (most recent call last):
  File "./gdal-summarize/gdal-summarize.py", line 290, in <module>
    main()
  File "./gdal-summarize/gdal-summarize.py", line 253, in main
    vals[vals == in_ndv[i]] = np_nan
ValueError: cannot convert float NaN to integer

**Comment by mstrimas** [comment]
Thanks for identifying this issue! I've never encountered this myself, would you be able to post some small files that reproduce the problem so I can investigate.

**Comment by dyoussef** [comment]
Hello, I got the same error. The problem occurs with integer type images and np_nan = np.nan (mean, median, max, meanz)

Maybe this patch could be integrated ? It works in my case.
```
diff --git a/gdal-summarize.py b/gdal-summarize.py
index b85a29c..e9fe736 100755
--- a/gdal-summarize.py
+++ b/gdal-summarize.py
@@ -247,7 +247,7 @@ def main():
             for i in range(len(stack)):
                 vals = gdalnumeric.BandReadAsArray(stack[i].GetRasterBand(args.bands[i]),
                                                    xoff = x_off, yoff = y_off,
-                                                   win_xsize = xvalid, win_ysize = yvalid)
+                                                   win_xsize = xvalid, win_ysize = yvalid).astype(out_type_np)
                 # fill in nodata values
                 if in_ndv[i] is not None:
                     vals[vals == in_ndv[i]] = np_nan
```

**Comment by mstrimas** [comment]
Thanks for suggesting this fix! Seems to work for me, so I've merged your change.
